*= $b129
TEXT_NOT_ENOUGH_MONEY:
    .text @"\$0d\$0d" + "THE KEYMASTER AND GATEKEEPER ARRIVED AT ZUUL ENDING THE GAME."
    .text " YOU DIDN'T MAKE ENOUGH MONEY SO THE BANK HAS FORECLOSED. BETTER LUCK NEXT TIME." + @"\$ff"

*= $b1b9
TEXT_GOOD_TRY:
    .text "GOOD TRY " + @"\$ff"

*= $b1c3
TEXT_FAILED_TO_CLOSE_PORTAL:
    .text "," + @"\$0d" + "BUT YOU FAILED TO CLOSE THE PORTAL TO THE SPIRIT WORLD AND ZUUL HAS TAKEN OVER YOUR CITY." + @"\$ff"

*= $b343
TEXT_STARTING_BALANCE:
    .text @"\$0d\$0d" + "STARTING BALANCE: " + @"\$ff"

*= $b358
TEXT_END_BALANCE:
    .text @"\$0d\$0d" + "  ENDING BALANCE: " + @"\$ff"