*= $b21f
TEXT_MADE_MORE_MONEY:
    .text @"\$0d\$0d" + "YOU MADE MORE MONEY THAN YOU STARTED WITH, SO THE BANK WILL RAISE YOUR CREDIT LIMIT TO " + @"\$ff"

*= $b279
TEXT_NEW_ACCOUNT_NUMBER:
    .text "." + @"\$0d\$0d" + "YOUR NEW ACCOUNT NUMBER IS " + @"\$ff"

*= $b298
TEXT_WRITE_DOWN_NUMBER:
    .text ". WRITE THIS NUMBER DOWN FOR FUTURE PLAY." + @"\$ff"

*= $b2c2
TEXT_CONGRATULATIONS:
    .text "CONGRATULATIONS" + @"\$28\$0d\$0d"
    .text "THANKS TO YOU, " + @"\$ff"

*= $b2e4
TEXT_PORTAL_CLOSED:
    .text @"\$0d" + "THE PORTAL TO THE SPIRIT WORLD HAS BEEN CLOSED. YOU EARN A $5000 REWARD FROM THE CITY. ALSO, " + @"\$ff"
